import { storage } from "@/sync/storage";
import { extractLatestOptions } from "@/hooks/useLatestOptions";
import {
    type AutoOptionSendContext,
    type AutoOptionSendEvent,
    type AutoOptionSendState,
    type SessionFollowUpOptionsSnapshot,
    buildAutoSentKey,
    buildOptionsHash,
    createInitialAutoOptionSendState,
    getRecommendedOptionIndex,
    rankAndSelectOptions,
    reduceAutoOptionSendEvent,
} from "@/-session/autoOptionSend";
import { type Message } from "@/sync/typesMessage";
import { hasPendingAskUserQuestion } from "./messageQueries";
import { getAutoOptionFeedbackStats, recordAutoOptionFeedback } from "./autoOptionFeedback";
import { projectManager } from "./projectManager";
import { log } from "@/log";
import { shouldPublishCountdownRemaining } from "./autoOptionCountdown";
import { scoreOptionsRemote } from "./apiOptionScore";
import { generateOptionsRemote } from "./apiOptionGenerate";
import { buildOptionScoringContext } from "@/-session/buildOptionScoringContext";
import { sync } from "./sync";
import { registerSessionScopedStore } from "./sessionScopedStore";

const DURATION_MS = 15_000;

/** localStorage key prefix for cross-tab send lock. */
const LOCK_PREFIX = "happy-aos-lock:";
/** BroadcastChannel name for cross-tab coordination. */
const CHANNEL_NAME = "happy-auto-option-send";
/** How long a localStorage lock stays valid (ms). */
const LOCK_TTL_MS = 30_000;

interface CrossTabMessage {
    type: "fired";
    tabId: string;
    sessionId: string;
    optionsHash: string;
}

interface SnapshotWithFreshness {
    snapshot: SessionFollowUpOptionsSnapshot;
    /** true when options come from the latest agent turn (no user message after). */
    isFresh: boolean;
}

function buildSnapshotFromMessages(
    messages: Message[],
): SnapshotWithFreshness | null {
    const result = extractLatestOptions(messages);
    if (result.items.length < 2) return null;

    // Determine freshness: options are fresh if no user-text appears before
    // the source message in the (newest-first) message list.
    let isFresh = true;
    if (result.sourceMessageId) {
        for (const msg of messages) {
            if (msg.id === result.sourceMessageId) break;
            if (msg.kind === "user-text") {
                isFresh = false;
                break;
            }
        }
    }

    return {
        snapshot: {
            sourceType: "markdown-options",
            sourceMessageId: result.sourceMessageId,
            items: result.items,
            recommendedIndex: getRecommendedOptionIndex(result.items),
            optionsHash: buildOptionsHash(result.items),
        },
        isFresh,
    };
}

interface UIContext {
    inputText: string;
    hasPendingImages: boolean;
    isSttListening: boolean;
}

const DEFAULT_UI_CONTEXT: UIContext = {
    inputText: "",
    hasPendingImages: false,
    isSttListening: false,
};

/**
 * All per-session state, keyed by sessionId in `this.sessions`. Collapsing the
 * formerly-parallel maps into one record makes two invariants correct-by-
 * construction: (1) `disposeSession` removes the whole record in one delete —
 * a new field can never be forgotten in cleanup; (2) the compiler enforces that
 * every per-session field lives here, so a field can't silently drift to a
 * different key (the bug that left `semanticScores`/`semanticMeta` — actually
 * keyed by optionsHash — leaking, since their per-session deletes never matched).
 *
 * Every field is optional: a record is created lazily by `ensure()` on the first
 * write, and read paths use `peek()` (no create) so a message arriving for an
 * untracked session never allocates a record.
 */
interface SessionAosRecord {
    state?: AutoOptionSendState;
    timer?: ReturnType<typeof setInterval>;
    listeners?: Set<() => void>;
    uiContext?: UIContext;
    semanticController?: AbortController;
    lastSemanticScoredAt?: number;
    passiveScoringController?: AbortController;
    lastPassiveScoredAt?: number;
    generatedOptions?: string[];
    lastGeneratedTurnId?: string | null;
    lastAutoGeneratedTurnId?: string | null;
    generationController?: AbortController;
    autoGenerationController?: AbortController;
    lastGeneratedAt?: number;
    lastPassiveGeneratedAt?: number;
}

class AutoOptionSendService {
    /** Per-session state — one record per session (see SessionAosRecord). */
    private sessions = new Map<string, SessionAosRecord>();
    private sendMessageFn:
        | ((
            sessionId: string,
            text: string,
            displayText?: string,
            options?: { source?: "auto-option-send" },
        ) => Promise<boolean | void>)
        | null = null;

    /** Unique ID for this tab/instance, used for cross-tab dedup. */
    private readonly tabId = Math.random().toString(36).slice(2, 10);
    /** BroadcastChannel for cross-tab coordination (web only). */
    private channel: BroadcastChannel | null = null;

    // ─── Global option-score caches (keyed by optionsHash, NOT sessionId) ───────
    // These are deliberately cross-session: the same option set scored once is
    // reused everywhere it appears. They are NOT part of SessionAosRecord and are
    // never cleared per-session (an earlier per-session delete here was dead code).
    private semanticScores = new Map<string, Map<number, number>>();
    private semanticMeta = new Map<string, { modelUsed: string; provider: string }>();
    private static readonly SEMANTIC_COOLDOWN_MS = 30_000;
    private static readonly SEMANTIC_SCORE_GAP_THRESHOLD = 8;

    private activeSessionId: string | null = null;
    /** Auto-send generation cooldown — turn dedup (lastAutoGeneratedTurnId) is the primary guard. */
    private static readonly GENERATION_COOLDOWN_MS = 10_000;
    /** Passive generation cooldown — also relies on turn dedup as primary guard. */
    private static readonly PASSIVE_GENERATION_COOLDOWN_MS = 5_000;

    /** Per-session record without creating one (read paths). */
    private peek(sessionId: string): SessionAosRecord | undefined {
        return this.sessions.get(sessionId);
    }

    /** Per-session record, creating an empty one on first write. */
    private ensure(sessionId: string): SessionAosRecord {
        let rec = this.sessions.get(sessionId);
        if (!rec) {
            rec = {};
            this.sessions.set(sessionId, rec);
        }
        return rec;
    }

    /** Returns the LLM scoring metadata (model + provider) for a given optionsHash, if available. */
    getSemanticMeta(optionsHash: string): { modelUsed: string; provider: string } | null {
        return this.semanticMeta.get(optionsHash) ?? null;
    }

    /** Returns proactively generated options for a session when no markdown options exist. */
    getGeneratedOptions(sessionId: string): string[] | null {
        const opts = this.peek(sessionId)?.generatedOptions;
        return opts && opts.length >= 2 ? opts : null;
    }

    /** Called once by sync.ts during init. */
    init(
        sendMessage: (
            sessionId: string,
            text: string,
            displayText?: string,
            options?: { source?: "auto-option-send" },
        ) => Promise<boolean | void>,
    ): void {
        this.sendMessageFn = sendMessage;
        const sessions =
            storage.getState().localSettings.autoOptionSendSessions ?? {};
        for (const [sessionId, enabled] of Object.entries(sessions)) {
            // Skip sessions already tracked in memory — a reconnect/restore call
            // must not clobber in-memory state (e.g. user toggled off via
            // context-invalidated but storage still shows enabled).
            if (enabled && this.peek(sessionId)?.state === undefined) {
                this.ensure(sessionId).state = {
                    ...createInitialAutoOptionSendState(),
                    enabled: true,
                    status: "idle",
                };
            }
        }

        // Cross-tab coordination (web only, no-op on React Native)
        if (typeof BroadcastChannel !== "undefined") {
            try {
                this.channel = new BroadcastChannel(CHANNEL_NAME);
                this.channel.onmessage = (event: MessageEvent) => {
                    this.handleCrossTabMessage(event.data);
                };
            } catch {
                // BroadcastChannel not supported or blocked
            }
        }
    }

    /** Called by sync.ts after new messages are applied for a session. */
    onMessages(sessionId: string): void {
        const rec = this.peek(sessionId);
        if (!rec?.state?.enabled) return;
        const state = rec.state;

        // Clear generated options when a new user message arrives (new turn started)
        const messages = storage.getState().sessionMessages[sessionId]?.messages ?? [];
        const latestMessage = messages[0];
        if (latestMessage?.kind === "user-text") {
            rec.generatedOptions = undefined;
            rec.generationController?.abort();
            rec.generationController = undefined;
            rec.autoGenerationController?.abort();
            rec.autoGenerationController = undefined;
            // New user turn starts: reset lastAutoSentKey so the next AI response can arm auto-send again
            if (state.lastAutoSentKey !== null) {
                rec.state = { ...state, lastAutoSentKey: null };
            }
        }

        this.checkAndDispatch(sessionId);
    }

    /** Called by sync.ts when a session reaches the ready (turn-end) state. */
    onReady(sessionId: string): void {
        const state = this.peek(sessionId)?.state;
        if (!state?.enabled) return;
        this.checkAndDispatch(sessionId);
    }

    /** Called by SessionView to keep the service aware of current UI state. */
    updateUIContext(sessionId: string, ctx: Partial<UIContext>): void {
        const rec = this.ensure(sessionId);
        rec.uiContext = { ...(rec.uiContext ?? DEFAULT_UI_CONTEXT), ...ctx };
    }

    /** Toggle auto-send for a session. Called from UI. */
    toggle(sessionId: string, enabled: boolean): void {
        const current =
            this.peek(sessionId)?.state ?? createInitialAutoOptionSendState();
        // When re-enabling, clear stale lastAutoSentKey — onMessages skips the
        // reset while disabled, so re-toggle would inherit a stale key that
        // blocks canFire from sending the same option set.
        const effective = enabled && current.lastAutoSentKey !== null
            ? { ...current, lastAutoSentKey: null }
            : current;
        const messages =
            storage.getState().sessionMessages[sessionId]?.messages ?? [];
        const result = buildSnapshotFromMessages(messages);
        const session = storage.getState().sessions[sessionId];
        const context = this.buildContext(sessionId, result?.snapshot ?? null, messages, Date.now());

        const next = reduceAutoOptionSendEvent(
            effective,
            { type: "toggle", enabled },
            context,
        );
        // Stale options (previous turn): skip countdown, stay idle
        const final =
            next.status === "armed" && result && !result.isFresh
                ? { ...next, status: "idle" as const, candidate: null, remainingMs: null }
                : next;
        this.applyStateChange(sessionId, current, final);
        this.persistEnabled(sessionId, final.enabled);

        console.log('[autoSend.toggle]', {
            enabled,
            finalStatus: final.status,
            nextStatus: next.status,
            sid: sessionId.slice(-8),
            hasSnapshot: !!result,
            isFresh: result?.isFresh,
            optionCount: result?.snapshot?.items?.length ?? 0,
            sessionActive: session?.active,
            sessionExists: !!session,
            msgCount: messages.length,
            prevStatus: current.status,
            lastSentKey: current.lastAutoSentKey?.slice(0, 30),
            ctxSnapshot: !!context.snapshot,
            ctxInput: context.inputText.length,
            ctxAskUQ: context.hasAskUserQuestionVisible,
        });
        // When enabling with no immediately-armable options, trigger checkAndDispatch so
        // proactive generation can start without waiting for the next onMessages/onReady.
        if (enabled && final.status === "idle") {
            // Reset turn dedup so a manual enable always triggers a fresh generation attempt,
            // even if the same turn was already tried (e.g. before auto-send was turned on).
            const rec = this.ensure(sessionId);
            rec.lastAutoGeneratedTurnId = undefined;
            rec.lastGeneratedAt = undefined;
            this.checkAndDispatch(sessionId);
        }
    }

    /**
     * Dispatch an arbitrary event from the UI (e.g. context-invalidated when
     * user starts typing while viewing the session).
     */
    dispatch(sessionId: string, event: AutoOptionSendEvent): void {
        const state = this.peek(sessionId)?.state;
        if (!state) return;
        const messages =
            storage.getState().sessionMessages[sessionId]?.messages ?? [];
        const result = buildSnapshotFromMessages(messages);
        const context = this.buildContext(sessionId, result?.snapshot ?? null, messages, Date.now());

        if (event.type === "context-invalidated" && event.reason === "options-missing" && state.candidate) {
            this.recordFeedbackFromCandidate(
                sessionId,
                state.candidate.optionsHash,
                state.candidate.recommendedText,
                "timeout_ignore",
                false,
                "auto",
                state.candidate.qualityScore,
                Date.now() - state.candidate.startedAt,
            );
        }

        const next = reduceAutoOptionSendEvent(state, event, context);
        this.applyStateChange(sessionId, state, next);
    }

    getState(sessionId: string): AutoOptionSendState {
        return this.peek(sessionId)?.state ?? createInitialAutoOptionSendState();
    }

    subscribe(sessionId: string, cb: () => void): () => void {
        const rec = this.ensure(sessionId);
        if (!rec.listeners) {
            rec.listeners = new Set();
        }
        rec.listeners.add(cb);
        return () => {
            this.peek(sessionId)?.listeners?.delete(cb);
        };
    }

    recordManualSend(
        sessionId: string,
        optionText: string,
        optionsHash: string,
        edited: boolean,
        source: "auto" | "manual",
    ): void {
        const state = this.peek(sessionId)?.state;
        const scoreBefore = state?.candidate?.recommendedText === optionText
            ? state.candidate.qualityScore
            : null;
        const latencyMs = state?.candidate?.recommendedText === optionText
            ? Date.now() - state.candidate.startedAt
            : null;

        this.recordFeedbackFromCandidate(
            sessionId,
            optionsHash,
            optionText,
            edited ? "edit_send" : "send",
            edited,
            source,
            scoreBefore,
            latencyMs,
        );
    }

    recordDismiss(
        sessionId: string,
        optionText: string | null,
        optionsHash: string | null,
    ): void {
        if (!optionText || !optionsHash) return;
        const state = this.peek(sessionId)?.state;
        const scoreBefore = state?.candidate?.recommendedText === optionText
            ? state.candidate.qualityScore
            : null;
        const latencyMs = state?.candidate?.recommendedText === optionText
            ? Date.now() - state.candidate.startedAt
            : null;

        this.recordFeedbackFromCandidate(
            sessionId,
            optionsHash,
            optionText,
            "dismiss",
            false,
            "manual",
            scoreBefore,
            latencyMs,
        );
    }

    disposeSession(sessionId: string): void {
        const rec = this.sessions.get(sessionId);
        if (rec) {
            // Abort every in-flight controller, stop the timer, then drop the
            // whole record in one delete — no per-field checklist to forget.
            if (rec.timer != null) clearInterval(rec.timer);
            rec.semanticController?.abort();
            rec.passiveScoringController?.abort();
            rec.generationController?.abort();
            rec.autoGenerationController?.abort();
            this.sessions.delete(sessionId);
        }
        // semanticScores / semanticMeta are keyed by optionsHash, not sessionId —
        // intentionally NOT cleared here (a previous per-session delete was a no-op).
        if (this.activeSessionId === sessionId) {
            this.activeSessionId = null;
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Private helpers
    // ──────────────────────────────────────────────────────────────────────────

    private checkAndDispatch(sessionId: string): void {
        const state = this.peek(sessionId)?.state;
        if (!state?.enabled) return;

        const messages =
            storage.getState().sessionMessages[sessionId]?.messages ?? [];
        const result = buildSnapshotFromMessages(messages);
        let snapshot = result?.snapshot ?? null;
        let isFresh = result?.isFresh ?? true;

        // Treat stale markdown options as absent so we fall through to generation.
        // Stale = user sent a message after the AI gave options (options are from previous turn).
        if (!isFresh) {
            snapshot = null;
        }

        // When no markdown options found (or stale), fall back to proactively generated options.
        if (!snapshot) {
            const generated = this.peek(sessionId)?.generatedOptions;
            if (generated && generated.length >= 2) {
                snapshot = {
                    sourceType: "markdown-options",
                    sourceMessageId: null,
                    items: generated,
                    recommendedIndex: getRecommendedOptionIndex(generated),
                    optionsHash: buildOptionsHash(generated),
                };
                isFresh = true;
            } else {
                // Kick off async generation; will re-run checkAndDispatch when ready.
                void this.triggerOptionGeneration(sessionId, messages);
            }
        }

        const context = this.buildContext(sessionId, snapshot, messages, Date.now());

        const event = snapshot
            ? ({ type: "options-updated" } as const)
            : ({ type: "context-invalidated", reason: "options-missing" } as const);

        const next = reduceAutoOptionSendEvent(state, event, context);
        // Stale options (previous turn): skip countdown, stay idle
        const final =
            next.status === "armed" && result && !isFresh
                ? { ...next, status: "idle" as const, candidate: null, remainingMs: null }
                : next;
        this.applyStateChange(sessionId, state, final);
    }

    private buildContext(
        sessionId: string,
        snapshot: SessionFollowUpOptionsSnapshot | null,
        messages: Message[],
        now: number,
    ): AutoOptionSendContext {
        const session = storage.getState().sessions[sessionId];
        const project = projectManager.getProjectForSession(sessionId);
        const projectId = project?.id ?? `session:${sessionId}`;
        const ui = this.peek(sessionId)?.uiContext ?? DEFAULT_UI_CONTEXT;
        return {
            sessionId,
            currentSessionId: sessionId,
            inputText: ui.inputText,
            hasPendingImages: ui.hasPendingImages,
            isSttListening: ui.isSttListening,
            hasAskUserQuestionVisible: hasPendingAskUserQuestion(messages),
            isCurrentSessionActive: session?.active ?? false,
            now,
            durationMs: DURATION_MS,
            snapshot,
            statsResolver: (optionText: string) =>
                getAutoOptionFeedbackStats(projectId, optionText),
        };
    }

    /** Apply a state transition and manage timer side-effects. */
    private applyStateChange(
        sessionId: string,
        prev: AutoOptionSendState,
        next: AutoOptionSendState,
    ): void {
        if (next === prev) return;

        const wasArmed = prev.status === "armed";
        const isArmed = next.status === "armed";

        this.setState(sessionId, next);

        if (isArmed && !wasArmed) {
            this.startTimer(sessionId);
            this.triggerSemanticScoring(sessionId);
        } else if (!isArmed && wasArmed) {
            this.clearTimer(sessionId);
            this.cancelSemanticScoring(sessionId);
        }
    }

    private startTimer(sessionId: string): void {
        this.clearTimer(sessionId);
        const interval = setInterval(() => {
            const state = this.peek(sessionId)?.state;
            if (!state || state.status !== "armed" || !state.candidate) {
                this.clearTimer(sessionId);
                return;
            }

            const remaining = Math.max(
                0,
                state.candidate.startedAt +
                    state.candidate.durationMs -
                    Date.now(),
            );

            const nextState = shouldPublishCountdownRemaining(
                state.remainingMs,
                remaining,
            )
                ? { ...state, remainingMs: remaining }
                : state;

            if (nextState !== state) {
                this.setState(sessionId, nextState);
            }

            if (remaining <= 0) {
                this.clearTimer(sessionId);
                // Capture the candidate identity so the deferred callback can verify
                // the state hasn't changed (re-armed or toggled off) in the interim.
                const firedHash = state.candidate.optionsHash;
                const firedStartedAt = state.candidate.startedAt;
                // Defer to next macrotask so any pending user events (e.g. toggle-off
                // clicks queued in the same 250 ms window) run first and can cancel.
                setTimeout(() => {
                    const latestState = this.peek(sessionId)?.state;
                    if (
                        !latestState ||
                        latestState.status !== "armed" ||
                        latestState.candidate?.optionsHash !== firedHash ||
                        latestState.candidate?.startedAt !== firedStartedAt
                    ) {
                        return;
                    }
                    this.fireTimerFinished(sessionId);
                }, 0);
            }
        }, 250);
        this.ensure(sessionId).timer = interval;
    }

    private clearTimer(sessionId: string): void {
        const rec = this.peek(sessionId);
        if (rec?.timer != null) {
            clearInterval(rec.timer);
            rec.timer = undefined;
        }
    }

    private cancelSemanticScoring(sessionId: string): void {
        const rec = this.peek(sessionId);
        if (rec?.semanticController) {
            rec.semanticController.abort();
            rec.semanticController = undefined;
        }
    }

    private cancelPassiveScoring(sessionId: string): void {
        const rec = this.peek(sessionId);
        if (rec?.passiveScoringController) {
            rec.passiveScoringController.abort();
            rec.passiveScoringController = undefined;
        }
    }

    private triggerSemanticScoring(sessionId: string): void {
        const state = this.peek(sessionId)?.state;
        if (!state?.candidate) return;

        const optionsHash = state.candidate.optionsHash;

        if (this.semanticScores.has(optionsHash)) return;

        const now = Date.now();
        const lastScored = this.peek(sessionId)?.lastSemanticScoredAt ?? 0;
        if (now - lastScored < AutoOptionSendService.SEMANTIC_COOLDOWN_MS) return;

        const messages =
            storage.getState().sessionMessages[sessionId]?.messages ?? [];
        const result = buildSnapshotFromMessages(messages);
        if (!result?.snapshot) return;

        const items = result.snapshot.items;
        const heuristicResult = rankAndSelectOptions(items);
        const scores = [...heuristicResult.allScores.values()];
        scores.sort((a, b) => b - a);

        // When auto-send is active for this session, always call LLM regardless of gap —
        // the model should be the primary decision-maker, not the heuristic.
        const isAutoSendActive = storage.getState().localSettings.autoOptionSendSessions?.[sessionId] === true;
        if (!isAutoSendActive && scores.length >= 2 && scores[0] - scores[1] > AutoOptionSendService.SEMANTIC_SCORE_GAP_THRESHOLD) return;

        const credentials = sync.getCredentials();
        if (!credentials) return;

        const session = storage.getState().sessions[sessionId];
        const sessionTitle = session?.metadata?.displayName ?? session?.metadata?.summary?.text ?? null;
        const contextSummary = buildOptionScoringContext(messages, sessionTitle);
        const controller = new AbortController();
        this.cancelSemanticScoring(sessionId);
        const rec = this.ensure(sessionId);
        rec.semanticController = controller;
        rec.lastSemanticScoredAt = now;

        const profileId = session?.profileId ?? null;
        const scoringOverrides = storage.getState().localSettings.scoringModelOverride ?? {};
        // When auto-send is enabled, prefer the highest available model unless user has set a custom override.
        const autoSendPreferredModels: Record<string, string> = {
            anthropic: "claude-opus-5",
            openai: "gpt-4.5",
        };
        const effectiveOverrides = Object.keys(scoringOverrides).length > 0
            ? scoringOverrides
            : isAutoSendActive ? autoSendPreferredModels : {};
        const modelOverride = Object.keys(effectiveOverrides).length > 0
            ? JSON.stringify(effectiveOverrides)
            : null;

        scoreOptionsRemote(credentials, items, contextSummary, null, profileId, modelOverride, controller.signal)
            .then((response) => {
                const recOnDone = this.peek(sessionId);
                if (recOnDone) recOnDone.semanticController = undefined;

                const current = recOnDone?.state;
                if (!current || current.status !== "armed" || !current.candidate) return;
                if (current.candidate.optionsHash !== optionsHash) return;

                const semanticMap = new Map<number, number>();
                response.scores.forEach((s, i) => semanticMap.set(i, s));
                this.semanticScores.set(optionsHash, semanticMap);
                if (response.modelUsed && response.provider) {
                    this.semanticMeta.set(optionsHash, { modelUsed: response.modelUsed, provider: response.provider });
                }

                const projectId = this.resolveProjectId(sessionId);
                const statsResolver = (optionText: string) =>
                    getAutoOptionFeedbackStats(projectId, optionText);
                const reranked = rankAndSelectOptions(items, statsResolver, undefined, semanticMap);

                const scoringMeta = (response.modelUsed && response.provider)
                    ? { modelUsed: response.modelUsed, provider: response.provider }
                    : undefined;
                if (reranked.recommendedIndex !== null) {
                    const selected = reranked.ranked.find((item) => item.index === reranked.recommendedIndex);
                    if (selected && selected.text !== current.candidate.recommendedText) {
                        this.setState(sessionId, {
                            ...current,
                            candidate: {
                                ...current.candidate,
                                recommendedText: selected.text,
                                qualityScore: selected.score,
                                qualityReasons: selected.reasons,
                                scoringMeta,
                            },
                        });
                    } else if (scoringMeta && !current.candidate.scoringMeta) {
                        this.setState(sessionId, {
                            ...current,
                            candidate: { ...current.candidate, scoringMeta },
                        });
                    }
                }
            })
            .catch(() => {
                const recOnErr = this.peek(sessionId);
                if (recOnErr) recOnErr.semanticController = undefined;
            });
    }

    private fireTimerFinished(sessionId: string): void {
        const state = this.peek(sessionId)?.state;
        if (!state || state.status !== "armed") return;

        const messages =
            storage.getState().sessionMessages[sessionId]?.messages ?? [];
        const result = buildSnapshotFromMessages(messages);
        const now = Date.now();
        // Fall back to generatedOptions when no markdown options exist,
        // so canFire's isContextReady check passes for AI-generated candidates.
        let snapshotForFire = result?.snapshot ?? null;
        if (!snapshotForFire) {
            const generated = this.peek(sessionId)?.generatedOptions;
            if (generated && generated.length >= 2) {
                snapshotForFire = {
                    sourceType: "markdown-options",
                    sourceMessageId: null,
                    items: generated,
                    recommendedIndex: getRecommendedOptionIndex(generated),
                    optionsHash: buildOptionsHash(generated),
                };
            }
        }
        // If LLM semantic scoring completed during the countdown, apply its recommendation
        // before firing. This fixes the race where heuristic-ranked option is sent even
        // though LLM ranked a different option higher.
        let currentState = state;
        if (state.candidate && snapshotForFire) {
            const semanticScores = this.semanticScores.get(state.candidate.optionsHash);
            if (semanticScores) {
                const reranked = rankAndSelectOptions(snapshotForFire.items, undefined, undefined, semanticScores);
                const best = reranked.recommendedIndex !== null
                    ? reranked.ranked.find((r) => r.index === reranked.recommendedIndex)
                    : null;
                if (best && best.text !== state.candidate.recommendedText) {
                    currentState = {
                        ...state,
                        candidate: {
                            ...state.candidate,
                            recommendedText: best.text,
                            qualityScore: best.score,
                            qualityReasons: best.reasons,
                        },
                    };
                    this.ensure(sessionId).state = currentState;
                }
            }
        }

        const context = this.buildContext(sessionId, snapshotForFire, messages, now);

        const readyState = reduceAutoOptionSendEvent(
            currentState,
            { type: "timer-finished" },
            context,
        );
        if (readyState.status !== "ready") {
            this.setState(sessionId, readyState);
            return;
        }

        const firedState = reduceAutoOptionSendEvent(
            readyState,
            { type: "attempt-fire" },
            context,
        );

        // Clear shouldSendText before notifying UI
        const textToSend = firedState.shouldSendText;
        const optionsHash = state.candidate?.optionsHash ?? "";
        this.setState(sessionId, { ...firedState, shouldSendText: null });

        if (textToSend) {
            // Cross-tab dedup: try to acquire localStorage lock
            if (!this.acquireSendLock(sessionId, optionsHash)) {
                return;
            }

            // Notify other tabs to cancel their timers
            this.broadcastFired(sessionId, optionsHash);

            const prevAutoSentKey = firedState.lastAutoSentKey;

            this.sendMessageFn?.(sessionId, textToSend, undefined, {
                source: "auto-option-send",
            }).then(() => {
                this.recordFeedbackFromCandidate(
                    sessionId,
                    optionsHash,
                    textToSend,
                    "send",
                    false,
                    "auto",
                    state.candidate?.qualityScore ?? null,
                    state.candidate ? now - state.candidate.startedAt : null,
                );
            }).catch(() => {
                log.warn("auto-option-send: sendMessage failed, resetting state for retry");
                this.recordFeedbackFromCandidate(
                    sessionId,
                    optionsHash,
                    textToSend,
                    "timeout_ignore",
                    false,
                    "auto",
                    state.candidate?.qualityScore ?? null,
                    state.candidate ? now - state.candidate.startedAt : null,
                );
                const current = this.peek(sessionId)?.state;
                if (current) {
                    this.setState(sessionId, {
                        ...current,
                        lastAutoSentKey: prevAutoSentKey,
                        lastAutoSentText: current.lastAutoSentText,
                    });
                }
            });
        } else if (state.candidate) {
            this.recordFeedbackFromCandidate(
                sessionId,
                state.candidate.optionsHash,
                state.candidate.recommendedText,
                "timeout_ignore",
                false,
                "auto",
                state.candidate.qualityScore,
                now - state.candidate.startedAt,
            );
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Cross-tab coordination
    // ──────────────────────────────────────────────────────────────────────────

    /**
     * Handle a message from another tab via BroadcastChannel.
     * If another tab already fired for the same session+options, cancel our timer.
     */
    private handleCrossTabMessage(data: unknown): void {
        if (!data || typeof data !== "object") return;
        const msg = data as CrossTabMessage;
        if (msg.type !== "fired" || msg.tabId === this.tabId) return;

        const state = this.peek(msg.sessionId)?.state;
        if (!state) return;
        if (state.status !== "armed" && state.status !== "ready") return;
        if (state.candidate?.optionsHash !== msg.optionsHash) return;

        // Another tab already sent this option — cancel our countdown
        this.clearTimer(msg.sessionId);
        this.setState(msg.sessionId, {
            ...state,
            status: "idle",
            candidate: null,
            remainingMs: null,
            lastAutoSentKey: state.candidate
                ? buildAutoSentKey(state.candidate)
                : state.lastAutoSentKey,
            lastAutoSentText:
                state.candidate?.recommendedText ?? state.lastAutoSentText,
            lastCancelReason: "sent-by-other-tab",
            shouldSendText: null,
        });
    }

    /** Broadcast to other tabs that we fired for this session+options. */
    private broadcastFired(sessionId: string, optionsHash: string): void {
        try {
            this.channel?.postMessage({
                type: "fired",
                tabId: this.tabId,
                sessionId,
                optionsHash,
            } satisfies CrossTabMessage);
        } catch {
            // Channel closed or unavailable
        }
    }

    /**
     * Try to claim a send lock via localStorage. Returns true if this tab
     * should proceed with sending (no other tab sent the same options recently).
     *
     * localStorage read→write is NOT atomic across tabs. Two tabs reaching
     * countdown zero within the same event-loop tick can both read "no lock"
     * and both write their own lock, causing duplicate sends. The write-then-
     * re-read check below shrinks this window (only a sub-millisecond overlap
     * between setItem calls can bypass it). BroadcastChannel provides an
     * additional async defense layer.
     */
    private acquireSendLock(
        sessionId: string,
        optionsHash: string,
    ): boolean {
        if (typeof localStorage === "undefined") return true; // React Native

        const key = `${LOCK_PREFIX}${sessionId}`;
        const now = Date.now();

        try {
            const raw = localStorage.getItem(key);
            if (raw) {
                const lock = JSON.parse(raw) as {
                    hash: string;
                    ts: number;
                    tabId: string;
                };
                if (
                    lock.hash === optionsHash &&
                    lock.tabId !== this.tabId &&
                    now - lock.ts < LOCK_TTL_MS
                ) {
                    return false;
                }
            }
        } catch {
            // Corrupt data, proceed and overwrite
        }

        // Claim the lock, then re-read to detect concurrent writers
        const lockValue = JSON.stringify({ hash: optionsHash, ts: now, tabId: this.tabId });
        localStorage.setItem(key, lockValue);

        try {
            const reRead = localStorage.getItem(key);
            if (reRead !== lockValue) {
                const winner = JSON.parse(reRead!) as { tabId: string };
                if (winner.tabId !== this.tabId) {
                    return false;
                }
            }
        } catch {
            // Parse failure on re-read — assume we hold the lock
        }

        return true;
    }

    private setState(sessionId: string, state: AutoOptionSendState): void {
        this.ensure(sessionId).state = state;
        this.notify(sessionId);
    }

    private notify(sessionId: string): void {
        const cbs = this.peek(sessionId)?.listeners;
        if (!cbs || cbs.size === 0) return;
        for (const cb of cbs) {
            cb();
        }
    }

    private persistEnabled(sessionId: string, enabled: boolean): void {
        const current =
            storage.getState().localSettings.autoOptionSendSessions ?? {};
        if (enabled) {
            if (current[sessionId] !== true) {
                storage.getState().applyLocalSettings({
                    autoOptionSendSessions: { ...current, [sessionId]: true },
                });
            }
        } else {
            if (current[sessionId] != null) {
                const { [sessionId]: _, ...rest } = current;
                storage.getState().applyLocalSettings({
                    autoOptionSendSessions: rest,
                });
            }
        }
    }

    getSemanticScores(optionsHash: string): ReadonlyMap<number, number> | null {
        return this.semanticScores.get(optionsHash) ?? null;
    }

    /**
     * Trigger LLM scoring for the given options without requiring auto-send to be enabled.
     * Used to show AI-scored badges (✨) in OptionsPopover for any session with 2+ options.
     */
    triggerScoringIfNeeded(sessionId: string, items: string[], optionsHash: string): void {
        if (items.length < 2) return;
        if (this.semanticScores.has(optionsHash)) return;

        const now = Date.now();
        const lastScored = this.peek(sessionId)?.lastPassiveScoredAt ?? 0;
        if (now - lastScored < AutoOptionSendService.SEMANTIC_COOLDOWN_MS) return;

        const credentials = sync.getCredentials();
        if (!credentials) return;

        const session = storage.getState().sessions[sessionId];
        if (!session) return;

        const messages = storage.getState().sessionMessages[sessionId]?.messages ?? [];
        const sessionTitle = session.metadata?.displayName ?? session.metadata?.summary?.text ?? null;
        const contextSummary = buildOptionScoringContext(messages, sessionTitle);
        const profileId = session.profileId ?? null;

        const scoringOverrides = storage.getState().localSettings.scoringModelOverride ?? {};
        const modelOverride = Object.keys(scoringOverrides).length > 0
            ? JSON.stringify(scoringOverrides)
            : null;

        const controller = new AbortController();
        this.cancelPassiveScoring(sessionId);
        const rec = this.ensure(sessionId);
        rec.passiveScoringController = controller;
        rec.lastPassiveScoredAt = now;

        scoreOptionsRemote(credentials, items, contextSummary, null, profileId, modelOverride, controller.signal)
            .then((response) => {
                const recOnDone = this.peek(sessionId);
                if (recOnDone) recOnDone.passiveScoringController = undefined;
                if (this.semanticScores.has(optionsHash)) return;

                const semanticMap = new Map<number, number>();
                response.scores.forEach((s, i) => semanticMap.set(i, s));
                this.semanticScores.set(optionsHash, semanticMap);
                if (response.modelUsed && response.provider) {
                    this.semanticMeta.set(optionsHash, { modelUsed: response.modelUsed, provider: response.provider });
                }
                // Shallow-copy state to produce new reference, forcing useMemo recompute in SessionView
                const current = this.peek(sessionId)?.state;
                if (current) {
                    this.setState(sessionId, { ...current });
                } else {
                    this.notify(sessionId);
                }
            })
            .catch(() => {
                const recOnErr = this.peek(sessionId);
                if (recOnErr) recOnErr.passiveScoringController = undefined;
            });
    }

    /**
     * Trigger LLM option generation without requiring auto-send to be enabled.
     * Used when there are no markdown options, so any session can get AI-suggested next steps.
     */
    triggerGenerationIfNeeded(sessionId: string): void {
        const session = storage.getState().sessions[sessionId];
        if (!session) return;

        const messages = storage.getState().sessionMessages[sessionId]?.messages ?? [];
        if (hasPendingAskUserQuestion(messages)) return;

        const latestAgentMsg = messages.find((m) => m.kind === "agent-text" && !("isThinking" in m && m.isThinking));
        const turnId = latestAgentMsg?.id ?? null;
        if (turnId && this.peek(sessionId)?.lastGeneratedTurnId === turnId) return;

        const now = Date.now();
        const lastAt = this.peek(sessionId)?.lastPassiveGeneratedAt ?? 0;
        if (now - lastAt < AutoOptionSendService.PASSIVE_GENERATION_COOLDOWN_MS) return;

        const credentials = sync.getCredentials();
        if (!credentials) return;

        const rec = this.ensure(sessionId);
        rec.lastGeneratedTurnId = turnId;
        rec.lastPassiveGeneratedAt = now;

        const sessionTitle = session.metadata?.displayName ?? session.metadata?.summary?.text ?? null;
        const contextSummary = buildOptionScoringContext(messages, sessionTitle);
        const profileId = session.profileId ?? null;

        const preferredModels: Record<string, string> = {
            anthropic: "claude-opus-5",
            openai: "gpt-4.5",
        };

        const controller = new AbortController();
        rec.generationController?.abort();
        rec.generationController = controller;

        generateOptionsRemote(
            credentials,
            contextSummary,
            null,
            profileId,
            JSON.stringify(preferredModels),
            controller.signal,
        ).then((result) => {
            const recOnDone = this.peek(sessionId);
            if (recOnDone) recOnDone.generationController = undefined;
            if (result.options.length >= 2) {
                this.ensure(sessionId).generatedOptions = result.options;
                const current = this.peek(sessionId)?.state;
                if (current) {
                    this.setState(sessionId, { ...current });
                } else {
                    this.notify(sessionId);
                }
                this.checkAndDispatch(sessionId);
            }
        }).catch(() => {
            const recOnErr = this.peek(sessionId);
            if (recOnErr) recOnErr.generationController = undefined;
        });
    }

    private async triggerOptionGeneration(sessionId: string, messages: Message[]): Promise<void> {
        const state = this.peek(sessionId)?.state;
        console.log('[autoSend.gen]', 'triggerOptionGeneration', { enabled: state?.enabled, sid: sessionId.slice(-8) });
        if (!state?.enabled) return;

        // Only generate when session exists (not archived)
        const session = storage.getState().sessions[sessionId];
        if (!session) { console.log('[autoSend.gen] no session'); return; }

        // Don't generate if there's a pending AskUserQuestion
        if (hasPendingAskUserQuestion(messages)) { console.log('[autoSend.gen] hasAskUserQ'); return; }

        // Use latest agent-text message id as turn identifier to avoid re-generating
        const latestAgentMsg = messages.find((m) => m.kind === "agent-text" && !("isThinking" in m && m.isThinking));
        const turnId = latestAgentMsg?.id ?? null;
        const turnCached = this.peek(sessionId)?.lastAutoGeneratedTurnId;
        console.log('[autoSend.gen] turnDedup', { turnId: turnId?.slice(-8), cached: turnCached?.slice(-8) });
        if (turnId && turnCached === turnId) return;

        // Cooldown: don't generate more often than every 2 minutes
        const now = Date.now();
        const lastAt = this.peek(sessionId)?.lastGeneratedAt ?? 0;
        const elapsed = now - lastAt;
        console.log('[autoSend.gen] cooldown', { elapsed, blocked: elapsed < AutoOptionSendService.GENERATION_COOLDOWN_MS });
        if (now - lastAt < AutoOptionSendService.GENERATION_COOLDOWN_MS) return;

        // Check credentials BEFORE marking this turn, so a null-credentials early exit
        // doesn't permanently lock out this turn via lastAutoGeneratedTurnId.
        const credentials = sync.getCredentials();
        console.log('[autoSend.gen] credentials', !!credentials);
        if (!credentials) return;

        // Mark this turn so we don't re-generate (auto-send has its own turn tracking)
        const rec = this.ensure(sessionId);
        rec.lastAutoGeneratedTurnId = turnId;
        rec.lastGeneratedAt = now;

        const sessionTitle = session.metadata?.displayName ?? session.metadata?.summary?.text ?? null;
        const contextSummary = buildOptionScoringContext(messages, sessionTitle);
        const profileId = session.profileId ?? null;

        // Prefer high-quality model for proactive generation
        const preferredModels: Record<string, string> = {
            anthropic: "claude-opus-5",
            openai: "gpt-4.5",
        };

        const controller = new AbortController();
        rec.autoGenerationController?.abort();
        rec.autoGenerationController = controller;

        try {
            const result = await generateOptionsRemote(
                credentials,
                contextSummary,
                null,
                profileId,
                JSON.stringify(preferredModels),
                controller.signal,
            );
            const recOnDone = this.peek(sessionId);
            if (recOnDone) recOnDone.autoGenerationController = undefined;

            if (result.options.length >= 2) {
                this.ensure(sessionId).generatedOptions = result.options;
                // Re-run checkAndDispatch now that we have generated options
                this.checkAndDispatch(sessionId);
            }
        } catch {
            const recOnErr = this.peek(sessionId);
            if (recOnErr) recOnErr.autoGenerationController = undefined;
        }
    }

    private resolveProjectId(sessionId: string): string {
        const project = projectManager.getProjectForSession(sessionId);
        return project?.id ?? `session:${sessionId}`;
    }

    private recordFeedbackFromCandidate(
        sessionId: string,
        optionsHash: string,
        optionText: string,
        action: "send" | "edit_send" | "timeout_ignore" | "dismiss",
        edited: boolean,
        source: "auto" | "manual",
        scoreBefore: number | null,
        latencyMs: number | null,
    ): void {
        const projectId = this.resolveProjectId(sessionId);
        recordAutoOptionFeedback({
            projectId,
            sessionId,
            optionText,
            optionHash: optionsHash,
            action,
            source,
            scoreBefore,
            latencyMs,
            edited,
            reason: null,
            ts: Date.now(),
        });
    }
}

export function createAutoOptionSendServiceForTesting(): AutoOptionSendService {
    return new AutoOptionSendService();
}

export const autoOptionSendService = new AutoOptionSendService();
registerSessionScopedStore(autoOptionSendService);
