import * as z from "zod";

// ===== Knowledge Entry Type =====
export const KnowledgeEntryTypeSchema = z.enum([
  "discovery",   // New insight or finding
  "decision",    // Architecture / tech choice
  "fix",         // Bug fix record
  "convention",  // Code convention / process rule
  "warning",     // Known pitfall or gotcha
  "repo_map",    // Static repo structure snapshot (file tree + key exports)
  "summary",     // Session-end summary (auto-generated at session teardown)
]);
export type KnowledgeEntryType = z.infer<typeof KnowledgeEntryTypeSchema>;

// ===== Contributor Type (multi-contributor ready) =====
export const KnowledgeContributorTypeSchema = z.enum([
  "session",     // Auto-generated by Claude session
  "supervisor",  // Generated by Supervisor analysis
  "user",        // Manually added by user
]);
export type KnowledgeContributorType = z.infer<typeof KnowledgeContributorTypeSchema>;

// ===== Knowledge Action (collaborative evolution ready) =====
export const KnowledgeActionSchema = z.enum([
  "create",      // New entry
  "amend",       // Correction / supplement
  "supersede",   // Replace old knowledge
  "verify",      // Confirm still valid
]);
export type KnowledgeAction = z.infer<typeof KnowledgeActionSchema>;

// ===== Knowledge Status =====
export const KnowledgeStatusSchema = z.enum([
  "active",      // Currently valid
  "superseded",  // Replaced by newer knowledge
  "archived",    // Manually archived by user
]);
export type KnowledgeStatus = z.infer<typeof KnowledgeStatusSchema>;

// ===== Confidence Level =====
export const KnowledgeConfidenceSchema = z.enum(["high", "medium", "low"]);
export type KnowledgeConfidence = z.infer<typeof KnowledgeConfidenceSchema>;

// ===== Create Knowledge Entry Body =====
export const CreateKnowledgeEntryBodySchema = z.object({
  entryType: KnowledgeEntryTypeSchema,
  contributorType: KnowledgeContributorTypeSchema,
  action: KnowledgeActionSchema,
  title: z.string().min(1).max(200),
  content: z.string().min(1),

  // Structured SOAP-like fields (optional)
  request: z.string().optional(),      // S: What the user asked
  findings: z.string().optional(),     // O: What was discovered
  analysis: z.string().optional(),     // A: Root cause / assessment
  outcome: z.string().optional(),      // P: What was done
  nextSteps: z.string().optional(),    // Follow-up suggestions

  tags: z.array(z.string().max(50)).max(20).default([]),
  confidence: KnowledgeConfidenceSchema.default("medium"),
  sessionId: z.string().optional(),
  model: z.string().optional(),
  supersedesId: z.string().optional(),
  relatedIds: z.array(z.string()).max(10).default([]),
  affectedFiles: z.array(z.string()).max(50).default([]),
});
export type CreateKnowledgeEntryBody = z.infer<typeof CreateKnowledgeEntryBodySchema>;

// ===== Update Knowledge Entry Body =====
export const UpdateKnowledgeEntryBodySchema = z.object({
  status: KnowledgeStatusSchema.optional(),
  pinned: z.boolean().optional(),
  title: z.string().min(1).max(200).optional(),
  content: z.string().min(1).optional(),
  tags: z.array(z.string().max(50)).max(20).optional(),
  confidence: KnowledgeConfidenceSchema.optional(),
});
export type UpdateKnowledgeEntryBody = z.infer<typeof UpdateKnowledgeEntryBodySchema>;

// ===== Query Knowledge Params =====
export const QueryKnowledgeParamsSchema = z.object({
  entryType: KnowledgeEntryTypeSchema.optional(),
  status: KnowledgeStatusSchema.optional(),
  tags: z.array(z.string()).optional(),
  search: z.string().max(500).optional(),
  limit: z.number().int().min(1).max(100).default(20),
  offset: z.number().int().min(0).default(0),
});
export type QueryKnowledgeParams = z.infer<typeof QueryKnowledgeParamsSchema>;

// ===== Project Profile =====
export const ProjectProfileSchema = z.object({
  techStack: z.array(z.string()),
  architectureType: z.string().optional(),
  knownPitfalls: z.array(z.string()),
  coreConventions: z.array(z.string()),
  lastUpdatedAt: z.number(),
  lastUpdatedBy: z.string().optional(),
});
export type ProjectProfile = z.infer<typeof ProjectProfileSchema>;

// ===== Knowledge Injection Request =====
export const KnowledgeInjectionModeSchema = z.enum(["auto", "full", "minimal"]);
export type KnowledgeInjectionMode = z.infer<typeof KnowledgeInjectionModeSchema>;

export const KnowledgeInjectionRequestSchema = z.object({
  mode: KnowledgeInjectionModeSchema,
  contextHints: z.array(z.string()).optional(), // Keywords from user message for relevance
});
export type KnowledgeInjectionRequest = z.infer<typeof KnowledgeInjectionRequestSchema>;

// ===== Knowledge Injection Response =====
export const KnowledgeInjectionResponseSchema = z.object({
  profile: ProjectProfileSchema.nullable(),
  entries: z.array(z.object({
    id: z.string(),
    entryType: KnowledgeEntryTypeSchema,
    title: z.string(),
    content: z.string(),
    tags: z.array(z.string()),
    confidence: KnowledgeConfidenceSchema,
    createdAt: z.string(),
  })),
});
export type KnowledgeInjectionResponse = z.infer<typeof KnowledgeInjectionResponseSchema>;

// ===== Knowledge Evolution Chain (Phase 2) =====
export const KnowledgeChainRelationSchema = z.object({
  from: z.string(),
  to: z.string(),
  type: z.enum(["supersedes", "related"]),
});
export type KnowledgeChainRelation = z.infer<typeof KnowledgeChainRelationSchema>;

export const KnowledgeChainEntrySchema = z.object({
  id: z.string(),
  entryType: KnowledgeEntryTypeSchema,
  action: KnowledgeActionSchema,
  status: KnowledgeStatusSchema,
  title: z.string(),
  content: z.string(),
  tags: z.array(z.string()),
  confidence: KnowledgeConfidenceSchema,
  supersedesId: z.string().nullable(),
  createdAt: z.string(),
});
export type KnowledgeChainEntry = z.infer<typeof KnowledgeChainEntrySchema>;

export const KnowledgeChainResponseSchema = z.object({
  chain: z.array(KnowledgeChainEntrySchema),
  relations: z.array(KnowledgeChainRelationSchema),
});
export type KnowledgeChainResponse = z.infer<typeof KnowledgeChainResponseSchema>;

// ===== Cross-Project Knowledge Search (Phase 2) =====
export const CrossProjectSearchResultSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  projectPath: z.string(),
  entryType: KnowledgeEntryTypeSchema,
  title: z.string(),
  content: z.string(),
  tags: z.array(z.string()),
  confidence: KnowledgeConfidenceSchema,
  similarity: z.number().optional(), // Present when using semantic search
  createdAt: z.string(),
});
export type CrossProjectSearchResult = z.infer<typeof CrossProjectSearchResultSchema>;

export const CrossProjectSearchResponseSchema = z.object({
  results: z.array(CrossProjectSearchResultSchema),
  total: z.number(),
});
export type CrossProjectSearchResponse = z.infer<typeof CrossProjectSearchResponseSchema>;

// ===== Turn Knowledge Extraction (CLI → Server) =====
export const TurnKnowledgeExtractionSchema = z.object({
  projectId: z.string(),
  sessionId: z.string(),
  model: z.string(),
  turnId: z.string(),
  turnData: z.object({
    userMessage: z.string().max(2000),
    assistantText: z.string().max(5000),
    fileEdits: z.array(z.object({
      path: z.string(),
      type: z.enum(["create", "edit"]),
    })).max(50),
    toolCallCount: z.number().int(),
    outputTokens: z.number().int(),
  }),
});
export type TurnKnowledgeExtraction = z.infer<typeof TurnKnowledgeExtractionSchema>;
