import { type Fastify } from "../types";
import { db } from "@/storage/db";
import { z } from "zod";
import { consolidate } from "@/modules/knowledgeConsolidate";
import { inTx } from "@/storage/inTx";
import { serializeKnowledgeEntry, parseProfileContent, safeParseJsonArray } from "@/modules/knowledgeSerialize";
import { storeKnowledgeEmbedding, findSimilarByEmbedding } from "@/modules/knowledgeEmbedding";
import { fetchKnowledgeChain } from "@/modules/knowledgeChain";
import { generateEmbedding, truncateForEmbedding } from "@/modules/embeddingService";
import { regenerateProfile } from "@/modules/knowledgeProfileGenerator";
import { trackKnowledgeCreation } from "@/modules/knowledgeAutoProfile";

// Inline Zod schemas (mirrors @kmmao/happy-wire/knowledge.ts)
// Server uses CommonJS resolution which can't import ESM-only wire values directly.

const KnowledgeEntryTypeEnum = z.enum(["discovery", "decision", "fix", "convention", "warning"]);
const KnowledgeContributorTypeEnum = z.enum(["session", "supervisor", "user"]);
const KnowledgeActionEnum = z.enum(["create", "amend", "supersede", "verify"]);
const KnowledgeStatusEnum = z.enum(["active", "superseded", "archived"]);
const KnowledgeConfidenceEnum = z.enum(["high", "medium", "low"]);

const CreateKnowledgeEntryBodySchema = z.object({
    entryType: KnowledgeEntryTypeEnum,
    contributorType: KnowledgeContributorTypeEnum,
    action: KnowledgeActionEnum,
    title: z.string().min(1).max(200),
    content: z.string().min(1),
    request: z.string().optional(),
    findings: z.string().optional(),
    analysis: z.string().optional(),
    outcome: z.string().optional(),
    nextSteps: z.string().optional(),
    tags: z.array(z.string().max(50)).max(20).default([]),
    confidence: KnowledgeConfidenceEnum.default("medium"),
    sessionId: z.string().optional(),
    model: z.string().optional(),
    supersedesId: z.string().optional(),
    relatedIds: z.array(z.string()).max(10).default([]),
    affectedFiles: z.array(z.string()).max(50).default([]),
});

const UpdateKnowledgeEntryBodySchema = z.object({
    status: KnowledgeStatusEnum.optional(),
    pinned: z.boolean().optional(),
    title: z.string().min(1).max(200).optional(),
    content: z.string().min(1).optional(),
    tags: z.array(z.string().max(50)).max(20).optional(),
    confidence: KnowledgeConfidenceEnum.optional(),
});

const QueryKnowledgeParamsSchema = z.object({
    entryType: KnowledgeEntryTypeEnum.optional(),
    status: KnowledgeStatusEnum.optional(),
    tags: z.preprocess(
        (val) => typeof val === "string" ? val.split(",") : val,
        z.array(z.string()).optional(),
    ),
    search: z.string().optional(),
    limit: z.coerce.number().int().min(1).max(100).default(20),
    offset: z.coerce.number().int().min(0).default(0),
});

const KnowledgeInjectionRequestSchema = z.object({
    mode: z.enum(["auto", "full", "minimal"]),
    contextHints: z.array(z.string()).optional(),
});

/**
 * Project knowledge base routes.
 * Provides CRUD for knowledge entries and project profiles.
 * Knowledge entries are auto-generated by CLI at turn-end and
 * consolidated with Mem0-style ADD/UPDATE/NOOP deduplication.
 */
export function knowledgeRoutes(app: Fastify) {
    // ─── List knowledge entries (paginated + filtered) ───
    app.get(
        "/v1/projects/:id/knowledge",
        {
            preHandler: app.authenticate,
            schema: {
                params: z.object({ id: z.string() }),
                querystring: QueryKnowledgeParamsSchema,
            },
        },
        async (request, reply) => {
            const userId = request.userId;
            const { id } = request.params;
            const { entryType, status, tags, search, limit, offset } = request.query;

            const project = await db.project.findFirst({
                where: { id, accountId: userId },
            });
            if (!project) {
                return reply.code(404).send({ error: "Project not found" });
            }

            const where: Record<string, unknown> = {
                projectId: id,
            };
            if (entryType) where.entryType = entryType;
            if (status) {
                where.status = status;
            } else {
                where.status = "active"; // Default to active only
            }
            if (search) {
                where.title = { contains: search, mode: "insensitive" };
            }

            const [entries, total] = await Promise.all([
                db.projectKnowledge.findMany({
                    where,
                    orderBy: [{ pinned: "desc" }, { createdAt: "desc" }],
                    take: limit,
                    skip: offset,
                }),
                db.projectKnowledge.count({ where }),
            ]);

            // Filter by tags in application layer (JSON array stored as string)
            const filtered = tags && tags.length > 0
                ? entries.filter((e) => {
                    const entryTags = safeParseJsonArray(e.tags);
                    return tags.some((t) => entryTags.includes(t));
                })
                : entries;

            return reply.send({
                entries: filtered.map(serializeKnowledgeEntry),
                total,
                limit,
                offset,
            });
        },
    );

    // ─── Create knowledge entry (with dedup) ───
    app.post(
        "/v1/projects/:id/knowledge",
        {
            preHandler: app.authenticate,
            schema: {
                params: z.object({ id: z.string() }),
                body: CreateKnowledgeEntryBodySchema,
            },
        },
        async (request, reply) => {
            const userId = request.userId;
            const { id } = request.params;
            const body = request.body;

            const project = await db.project.findFirst({
                where: { id, accountId: userId },
            });
            if (!project) {
                return reply.code(404).send({ error: "Project not found" });
            }

            // Mem0-style dedup: check for similar active entries
            const dedupAction = await consolidate(id, body);

            if (dedupAction.type === "noop") {
                return reply.send({ action: "noop", reason: dedupAction.reason });
            }

            const entry = await inTx(async (tx) => {
                if (dedupAction.type === "update") {
                    await tx.projectKnowledge.update({
                        where: { id: dedupAction.existingId },
                        data: { status: "superseded" },
                    });
                }

                return tx.projectKnowledge.create({
                    data: {
                        projectId: id,
                        entryType: body.entryType,
                        contributorType: body.contributorType,
                        action: dedupAction.type === "update" ? "supersede" : body.action,
                        title: body.title,
                        content: body.content,
                        structured: body.request || body.findings || body.analysis || body.outcome || body.nextSteps
                            ? JSON.stringify({
                                request: body.request,
                                findings: body.findings,
                                analysis: body.analysis,
                                outcome: body.outcome,
                                nextSteps: body.nextSteps,
                            })
                            : null,
                        tags: JSON.stringify(body.tags),
                        confidence: body.confidence,
                        model: body.model,
                        sessionId: body.sessionId,
                        affectedFiles: JSON.stringify(body.affectedFiles),
                        relatedIds: JSON.stringify(body.relatedIds),
                        supersedesId: dedupAction.type === "update" ? dedupAction.existingId : body.supersedesId,
                    },
                });
            });

            // Fire-and-forget: generate embedding for semantic search
            void storeKnowledgeEmbedding(entry.id, entry.title, entry.content);
            trackKnowledgeCreation(id);

            return reply.code(201).send({
                action: dedupAction.type,
                entry: serializeKnowledgeEntry(entry),
            });
        },
    );

    // ─── Update knowledge entry ───
    app.patch(
        "/v1/projects/:id/knowledge/:entryId",
        {
            preHandler: app.authenticate,
            schema: {
                params: z.object({ id: z.string(), entryId: z.string() }),
                body: UpdateKnowledgeEntryBodySchema,
            },
        },
        async (request, reply) => {
            const userId = request.userId;
            const { id, entryId } = request.params;
            const body = request.body;

            const project = await db.project.findFirst({
                where: { id, accountId: userId },
            });
            if (!project) {
                return reply.code(404).send({ error: "Project not found" });
            }

            const entry = await db.projectKnowledge.findFirst({
                where: { id: entryId, projectId: id },
            });
            if (!entry) {
                return reply.code(404).send({ error: "Knowledge entry not found" });
            }

            const data: Record<string, unknown> = {};
            if (body.status !== undefined) data.status = body.status;
            if (body.pinned !== undefined) data.pinned = body.pinned;
            if (body.title !== undefined) data.title = body.title;
            if (body.content !== undefined) data.content = body.content;
            if (body.tags !== undefined) data.tags = JSON.stringify(body.tags);
            if (body.confidence !== undefined) data.confidence = body.confidence;

            const updated = await db.projectKnowledge.update({
                where: { id: entryId },
                data,
            });

            return reply.send({ entry: serializeKnowledgeEntry(updated) });
        },
    );

    // ─── Delete knowledge entry ───
    app.delete(
        "/v1/projects/:id/knowledge/:entryId",
        {
            preHandler: app.authenticate,
            schema: {
                params: z.object({ id: z.string(), entryId: z.string() }),
            },
        },
        async (request, reply) => {
            const userId = request.userId;
            const { id, entryId } = request.params;

            const project = await db.project.findFirst({
                where: { id, accountId: userId },
            });
            if (!project) {
                return reply.code(404).send({ error: "Project not found" });
            }

            await db.projectKnowledge.delete({
                where: { id: entryId, projectId: id },
            });

            return reply.send({ success: true });
        },
    );

    // ─── Get project profile ───
    app.get(
        "/v1/projects/:id/profile",
        {
            preHandler: app.authenticate,
            schema: {
                params: z.object({ id: z.string() }),
            },
        },
        async (request, reply) => {
            const userId = request.userId;
            const { id } = request.params;

            const project = await db.project.findFirst({
                where: { id, accountId: userId },
            });
            if (!project) {
                return reply.code(404).send({ error: "Project not found" });
            }

            const profile = await db.projectProfile.findUnique({
                where: { projectId: id },
            });

            return reply.send({
                profile: profile
                    ? { ...profile, createdAt: profile.createdAt.getTime(), updatedAt: profile.updatedAt.getTime() }
                    : null,
            });
        },
    );

    // ─── Create/update project profile (optimistic locking) ───
    app.put(
        "/v1/projects/:id/profile",
        {
            preHandler: app.authenticate,
            schema: {
                params: z.object({ id: z.string() }),
                body: z.object({
                    content: z.string(),
                    expectedVersion: z.number().int().optional(),
                }),
            },
        },
        async (request, reply) => {
            const userId = request.userId;
            const { id } = request.params;
            const { content, expectedVersion } = request.body;

            const project = await db.project.findFirst({
                where: { id, accountId: userId },
            });
            if (!project) {
                return reply.code(404).send({ error: "Project not found" });
            }

            if (expectedVersion !== undefined) {
                // Atomic optimistic lock: update only if version matches
                const result = await inTx(async (tx) => {
                    const existing = await tx.projectProfile.findUnique({
                        where: { projectId: id },
                    });
                    if (!existing) return null;
                    if (existing.version !== expectedVersion) {
                        return { conflict: true, currentVersion: existing.version };
                    }
                    return tx.projectProfile.update({
                        where: { projectId: id },
                        data: { content, version: { increment: 1 } },
                    });
                });

                if (!result) {
                    // No existing profile — create
                    const created = await db.projectProfile.create({
                        data: { projectId: id, content },
                    });
                    return reply.code(201).send({ profile: created, version: created.version });
                }
                if ("conflict" in result) {
                    return reply.code(409).send({
                        error: "version-mismatch",
                        currentVersion: result.currentVersion,
                    });
                }
                return reply.send({ profile: result, version: result.version });
            }

            // No version check — upsert
            const result = await db.projectProfile.upsert({
                where: { projectId: id },
                create: { projectId: id, content },
                update: { content, version: { increment: 1 } },
            });
            const isNew = result.version === 1;
            return reply.code(isNew ? 201 : 200).send({ profile: result, version: result.version });
        },
    );

    // ─── Knowledge evolution chain ───
    app.get(
        "/v1/projects/:id/knowledge/:entryId/chain",
        {
            preHandler: app.authenticate,
            schema: {
                params: z.object({ id: z.string(), entryId: z.string() }),
            },
        },
        async (request, reply) => {
            const userId = request.userId;
            const { id, entryId } = request.params;

            const project = await db.project.findFirst({
                where: { id, accountId: userId },
            });
            if (!project) {
                return reply.code(404).send({ error: "Project not found" });
            }

            const entry = await db.projectKnowledge.findFirst({
                where: { id: entryId, projectId: id },
            });
            if (!entry) {
                return reply.code(404).send({ error: "Knowledge entry not found" });
            }

            const result = await fetchKnowledgeChain(id, entryId);
            return reply.send(result);
        },
    );

    // ─── Regenerate project profile ───
    app.post(
        "/v1/projects/:id/profile/regenerate",
        {
            preHandler: app.authenticate,
            schema: {
                params: z.object({ id: z.string() }),
            },
        },
        async (request, reply) => {
            const userId = request.userId;
            const { id } = request.params;

            const project = await db.project.findFirst({
                where: { id, accountId: userId },
            });
            if (!project) {
                return reply.code(404).send({ error: "Project not found" });
            }

            const result = await regenerateProfile(id);

            if (!result.success) {
                return reply.code(500).send({ error: result.error });
            }

            // Fetch the updated profile to return
            const profile = await db.projectProfile.findUnique({
                where: { projectId: id },
            });

            return reply.send({
                profile: profile
                    ? { ...profile, createdAt: profile.createdAt.getTime(), updatedAt: profile.updatedAt.getTime() }
                    : null,
                version: result.version,
            });
        },
    );

    // ─── Knowledge injection (for new sessions) ───
    app.post(
        "/v1/projects/:id/knowledge/inject",
        {
            preHandler: app.authenticate,
            schema: {
                params: z.object({ id: z.string() }),
                body: KnowledgeInjectionRequestSchema,
            },
        },
        async (request, reply) => {
            const userId = request.userId;
            const { id } = request.params;
            const { mode, contextHints } = request.body;

            const project = await db.project.findFirst({
                where: { id, accountId: userId },
            });
            if (!project) {
                return reply.code(404).send({ error: "Project not found" });
            }

            // Get project profile (L1)
            const profileRecord = await db.projectProfile.findUnique({
                where: { projectId: id },
            });
            const profile = profileRecord
                ? parseProfileContent(profileRecord.content)
                : null;

            if (mode === "minimal") {
                return reply.send({ profile, entries: [] });
            }

            // Determine how many entries to fetch
            const entryLimit = mode === "full" ? 20 : 5;

            let entries;
            if (contextHints && contextHints.length > 0) {
                // Try semantic search first, fall back to keyword matching
                const semanticEntries = await trySemanticInjection(id, contextHints, entryLimit);
                if (semanticEntries) {
                    entries = semanticEntries;
                } else {
                    // Keyword-based relevance search (fallback)
                    const allActive = await db.projectKnowledge.findMany({
                        where: { projectId: id, status: "active" },
                        orderBy: [{ pinned: "desc" }, { createdAt: "desc" }],
                        take: 100,
                    });
                    const scored = allActive.map((e) => {
                        const text = `${e.title} ${e.tags} ${e.content}`.toLowerCase();
                        const score = contextHints.reduce(
                            (acc, hint) => acc + (text.includes(hint.toLowerCase()) ? 1 : 0),
                            0,
                        );
                        return { entry: e, score };
                    });
                    scored.sort((a, b) => b.score - a.score || b.entry.createdAt.getTime() - a.entry.createdAt.getTime());
                    entries = scored.slice(0, entryLimit).map((s) => s.entry);
                }
            } else {
                entries = await db.projectKnowledge.findMany({
                    where: { projectId: id, status: "active" },
                    orderBy: [{ pinned: "desc" }, { createdAt: "desc" }],
                    take: entryLimit,
                });
            }

            return reply.send({
                profile,
                entries: entries.map((e) => ({
                    id: e.id,
                    entryType: e.entryType,
                    title: e.title,
                    content: e.content,
                    tags: safeParseJsonArray(e.tags),
                    confidence: e.confidence,
                    createdAt: e.createdAt.toISOString(),
                })),
            });
        },
    );
}

/**
 * Try to use embedding-based search for knowledge injection.
 * Returns null if embedding is unavailable (caller should fall back to keyword).
 */
async function trySemanticInjection(
    projectId: string,
    contextHints: string[],
    limit: number,
): Promise<Awaited<ReturnType<typeof db.projectKnowledge.findMany>> | null> {
    try {
        const queryText = truncateForEmbedding(contextHints.join(" "));
        const queryEmbedding = await generateEmbedding(queryText);
        if (!queryEmbedding) return null;

        const similar = await findSimilarByEmbedding(projectId, queryEmbedding, limit);
        if (similar.length === 0) return null;

        // Fetch full entries for the matched IDs
        const ids = similar.map((s) => s.id);
        const entries = await db.projectKnowledge.findMany({
            where: { id: { in: ids }, status: "active" },
            orderBy: [{ pinned: "desc" }, { createdAt: "desc" }],
        });

        // Re-sort by similarity order
        const idOrder = new Map(ids.map((id, i) => [id, i]));
        entries.sort((a, b) => (idOrder.get(a.id) ?? 999) - (idOrder.get(b.id) ?? 999));

        return entries;
    } catch {
        return null;
    }
}
