import { Platform } from "react-native";
import { StyleSheet } from "react-native-unistyles";
import { layout } from "@/components/layout";

export const styles = StyleSheet.create((theme) => ({
    container: {
        flex: 1,
        backgroundColor: theme.colors.surface,
    },
    content: {
        maxWidth: layout.maxWidth,
        width: "100%",
        alignSelf: "center",
        paddingBottom: 40,
    },
    rpcNotice: {
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: -4,
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.groupped.background,
        gap: 4,
    },
    rpcNoticeTitle: {
        color: theme.colors.text,
        fontSize: 14,
        fontWeight: "700",
    },
    rpcNoticeText: {
        color: theme.colors.textSecondary,
        fontSize: 12,
    },
    panelHeaderRow: {
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: 8,
    },
    panelHeaderTextCol: {
        flex: 1,
        gap: 4,
    },
    panelTitle: {
        color: theme.colors.text,
        fontSize: 16,
        fontWeight: "700",
    },
    panelSubtitle: {
        color: theme.colors.textSecondary,
        fontSize: 13,
        lineHeight: 18,
    },
    panelHint: {
        color: theme.colors.textSecondary,
        fontSize: 12,
        lineHeight: 17,
        marginTop: -2,
    },
    filterPanel: {
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: 8,
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.groupped.background,
        gap: 8,
    },
    searchInput: {
        borderRadius: 8,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.input?.background ?? theme.colors.surface,
        color: theme.colors.text,
        minHeight: 42,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    filterLabel: {
        color: theme.colors.textSecondary,
        fontSize: 13,
        fontWeight: "600",
    },
    filterChipRow: {
        flexDirection: "row",
        flexWrap: "nowrap",
        gap: 8,
        paddingRight: 12,
    },
    filterScroll: {
        flexGrow: 0,
    },
    filterChip: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.surface,
    },
    filterChipSelected: {
        borderColor: theme.colors.textLink,
        backgroundColor: theme.colors.textLink,
    },
    filterChipText: {
        color: theme.colors.text,
        fontSize: 13,
        fontWeight: "600",
    },
    filterChipTextSelected: {
        color: "#FFFFFF",
    },
    filterSummary: {
        color: theme.colors.textSecondary,
        fontSize: 12,
    },
    summaryGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
    },
    summaryCard: {
        width: Platform.OS === "web" ? "31.5%" : "47.5%",
        minHeight: 112,
        padding: 12,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.surface,
        gap: 6,
    },
    summaryCardTitle: {
        color: theme.colors.textSecondary,
        fontSize: 12,
        fontWeight: "600",
    },
    summaryCardValue: {
        color: theme.colors.text,
        fontSize: 26,
        fontWeight: "800",
    },
    summaryCardHint: {
        color: theme.colors.textSecondary,
        fontSize: 12,
        lineHeight: 17,
    },
    emptyCard: {
        marginHorizontal: 12,
        marginVertical: 8,
        padding: 14,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.surface,
        gap: 4,
    },
    emptyCardTitle: {
        color: theme.colors.text,
        fontSize: 14,
        fontWeight: "700",
    },
    emptyCardSubtitle: {
        color: theme.colors.textSecondary,
        fontSize: 12,
        lineHeight: 17,
    },
    dataCard: {
        marginHorizontal: 12,
        marginVertical: 6,
        padding: 14,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.surface,
        gap: 10,
    },
    dataCardHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 12,
        alignItems: "flex-start",
    },
    dataCardTitleWrap: {
        flex: 1,
        gap: 4,
    },
    dataCardTitle: {
        color: theme.colors.text,
        fontSize: 15,
        fontWeight: "700",
    },
    dataCardSubtitle: {
        color: theme.colors.textSecondary,
        fontSize: 13,
        lineHeight: 18,
    },
    dataCardTimestamp: {
        color: theme.colors.textSecondary,
        fontSize: 12,
        fontWeight: "600",
        textAlign: "right",
        maxWidth: 132,
    },
    pillRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    pill: {
        minHeight: 28,
        paddingHorizontal: 10,
        borderRadius: 999,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.colors.surfaceHigh ?? theme.colors.surface,
    },
    pillText: {
        color: theme.colors.textSecondary,
        fontSize: 12,
        fontWeight: "600",
    },
    statusWrap: {
        alignItems: "flex-end",
        gap: 8,
    },
    statusBadge: {
        minHeight: 28,
        paddingHorizontal: 10,
        borderRadius: 999,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    statusBadgeText: {
        fontSize: 12,
        fontWeight: "700",
    },
    timelineCard: {
        marginHorizontal: 12,
        marginVertical: 4,
        flexDirection: "row",
        gap: 10,
    },
    timelineRail: {
        width: 16,
        alignItems: "center",
    },
    timelineDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginTop: 10,
    },
    timelineLine: {
        width: 2,
        flex: 1,
        marginTop: 4,
        marginBottom: -4,
    },
    timelineContent: {
        flex: 1,
        padding: 12,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.surface,
    },
    centered: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.colors.surface,
    },
}));
